### ISSUE TITLE
Error while using --use-nonoverlapping-peaks option

### ISSUE THREAD

**Issue by mohammedmsk** [nboley/idr#14]
Hello,

Trying to use idr tool with this command:
/share/apps/idr/5fbd010/bin/idr \
--samples \
BRD2_minus_JQ1_1.MACS2_peaks.narrowPeak.IDR_ready.temp.Peak BRD2_minus_JQ1_2.MACS2_peaks.narrowPeak.IDR_ready.temp.Peak  \
--input-file-type narrowPeak \
--rank p.value \
--output-file test.merged.idr.bed \
--soft-idr-threshold 0.05 \
--plot \
--use-nonoverlapping-peaks \
--peak-merge-method min \
--verbose

Getting the following error:
Please see attached file: 
[TKXL.test.IDR.e293603.txt](https://github.com/nboley/idr/files/79189/TKXL.test.IDR.e293603.txt)

It works fine without any errors if I drop the --use-nonoverlapping-peaks option.

**Comment by nboley** [comment]
This is fixed in the newest version.
