### ISSUE TITLE
Motivation for parameter clipping

### ISSUE THREAD

**Issue by superbobry** [nboley/idr#19]
I've been reading `idr` sources to complement my understanding of the [paper] [*] by Li et al. One thing that caught my attention is predefined parameter ranges ranges in `__init__.py`. The paper doesn't mention any restrictions, so I would appreciate it if you could comment on why these are required and how the ranges were chosen for each parameter?

[*]: http://projecteuclid.org/euclid.aoas/1318514284

**Comment by nboley** [comment]
There's an identifiability problem in the model. For example, if unconstrained the sd can go to zero, which is effectively the same as the mixture parameter going to 0. I added the constraints to prevent this behavior. If the fit value is at the boundaries, then the model is probably not appropriate. Do you have examples or is the question academic?
