### ISSUE TITLE
error: Use a.any() or a.all()_

### ISSUE THREAD

**Issue by LunaPatton** [nboley/idr#57]
Hi
When I ran ATAC-Seq data with IDR and encountered below error for so many times.  so why it came?
**code:**
_idr --samples sample1_peaks.narrowPeak  sample2_peaks.narrowPeak \
--input-file-type narrowPeak \
--rank p.value \
--output-file $workdir/IDR/rep_idr \
--plot \
--log-output-file $workdir/IDR/rep.idr.log_

**error:**
_File "/mypathtodir/site-packages/idr-2.0.2-py3.8-linux-x86_64.egg/idr/idr.py", line 415, in write_results_to_file
    if localIDRs == None or IDRs == None:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()_

Thanks  !

Best wishes
Zoe

**Comment by LunaPatton** [comment]
@nboley

**Comment by IrisWEI-1996** [comment]
Hi I met a same problem using idr-2.0.2 and solved it by reinstalling idr-2.0.4 with Anaconda.

**Comment by LunaPatton** [comment]
> Hi I met a same problem using idr-2.0.2 and solved it by reinstalling idr-2.0.4 with Anaconda.

I solved this problem by installing idr-2.0.3. The reason why it occurred still unknow.
